// Objective-C API for talking to github.com/sger/gomobile-examples/mypackage Go package.
//   gobind -lang=objc github.com/sger/gomobile-examples/mypackage
//
// File is generated by gobind. Do not edit.

#ifndef __Mypackage_H__
#define __Mypackage_H__

@import Foundation;
#include "Universe.objc.h"


@protocol MypackageCallback;
@class MypackageCallback;

@protocol MypackageCallback <NSObject>
- (void)method1;
- (void)method2:(NSString*)p0;
@end

FOUNDATION_EXPORT NSString* MypackageLog(NSString* tag, NSString* msg);

FOUNDATION_EXPORT NSString* MypackageLogError(NSString* tag, NSString* str, NSError** error);

FOUNDATION_EXPORT void MypackageRegisterCallback(id<MypackageCallback> c);

@class MypackageCallback;

@interface MypackageCallback : NSObject <goSeqRefInterface, MypackageCallback> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)method1;
- (void)method2:(NSString*)p0;
@end

#endif
