
// Objective-C API for talking to the following Go packages
//
//	github.com/sger/gomobile-examples/mypackage
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mypackage_FRAMEWORK_H__
#define __Mypackage_FRAMEWORK_H__

#include "Mypackage.objc.h"
#include "Universe.objc.h"

#endif
