
// Objective-C API for talking to the following Go packages
//
//	github.com/sger/gomobile-examples/mypkg
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mypkg_FRAMEWORK_H__
#define __Mypkg_FRAMEWORK_H__

#include "Mypkg.objc.h"
#include "Universe.objc.h"

#endif
