// Objective-C API for talking to github.com/sger/gomobile-examples/mypkg Go package.
//   gobind -lang=objc github.com/sger/gomobile-examples/mypkg
//
// File is generated by gobind. Do not edit.

#ifndef __Mypkg_H__
#define __Mypkg_H__

@import Foundation;
#include "Universe.objc.h"


@class MypkgCounter;

@interface MypkgCounter : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (long)value;
- (void)setValue:(long)v;
- (void)inc;
@end

FOUNDATION_EXPORT MypkgCounter* MypkgNewCounter(void);

#endif
